# Generated by Django 4.0 on 2022-08-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_atendence_attendence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendence',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendence',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
